apiVersion: v1
kind: Service
metadata:
  name: nodejs
  labels:
    app: nodejs
    tier: frontend
spec:
  type: NodePort
  ports:
    - name: nodejs
      port: 3000
      targetPort: 3000
      nodePort: 30080
  selector:
    app: nodejs
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
  labels:
    app: nodejs
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs
      tier: frontend
  replicas: 3
  template:
    metadata:
      labels:
        app: nodejs
        tier: frontend
    spec:
      containers:
        - name: nodejs
          image: *
          imagePullPolicy: Always
          ports:
            - containerPort: 3000